#!/usr/bin/env bash
#
# Read an `InstallationPrepared` event and print the env lines `safe-apply-install` needs.
#
# `applyInstallation` re-derives the prepared setup id from the plugin address, the permission set
# and the helpers hash, and reverts on any mismatch. Those values only exist in the event the
# prepare transaction emitted, so they have to be carried across by hand — and a transposed
# permission or a reordered list fails on chain with nothing naming the field. This reads them
# straight from the receipt instead.
#
# Usage:
#   ./script/read-prepared.sh <tx-hash> <PREFIX> [rpc-url]
#
#   ./script/read-prepared.sh 0xabc… CRISP >> .env
#
# The permission order is preserved exactly as emitted: the setup id hashes the sequence, so
# sorting or de-duplicating the lists would invalidate them.
set -euo pipefail

TX_HASH="${1:?usage: read-prepared.sh <tx-hash> <PREFIX> [rpc-url]}"
PREFIX="${2:?usage: read-prepared.sh <tx-hash> <PREFIX> [rpc-url]}"
RPC="${3:-${RPC_URL:?set RPC_URL or pass it as the third argument}}"

command -v cast >/dev/null 2>&1 || { echo "error: cast not found (install foundry)" >&2; exit 1; }
command -v jq   >/dev/null 2>&1 || { echo "error: jq not found" >&2; exit 1; }

# keccak256("InstallationPrepared(address,address,bytes32,address,(uint8,uint16),bytes,address,(address[],(uint8,address,address,address,bytes32)[]))")
TOPIC="$(cast keccak 'InstallationPrepared(address,address,bytes32,address,(uint8,uint16),bytes,address,(address[],(uint8,address,address,address,bytes32)[]))')"

RECEIPT="$(cast receipt "${TX_HASH}" --rpc-url "${RPC}" --json)"

# One prepare per transaction is the expected shape. More than one and the caller must say which,
# so pick nothing rather than silently taking the first.
COUNT="$(echo "${RECEIPT}" | jq --arg t "${TOPIC}" '[.logs[] | select(.topics[0] == $t)] | length')"
if [[ "${COUNT}" == "0" ]]; then
  echo "error: no InstallationPrepared event in ${TX_HASH}" >&2
  echo "       (is this the prepare transaction, and did it succeed?)" >&2
  exit 1
fi
if [[ "${COUNT}" != "1" ]]; then
  echo "error: ${COUNT} InstallationPrepared events in one transaction; split them or extract by hand" >&2
  exit 1
fi

DATA="$(echo "${RECEIPT}" | jq -r --arg t "${TOPIC}" '.logs[] | select(.topics[0] == $t) | .data')"

# Non-indexed members, in order: preparedSetupId, versionTag, data, plugin, preparedSetupData.
# `sender`, `dao` and `pluginSetupRepo` are indexed and live in topics, not here.
DECODED="$(cast decode-abi \
  "x()((bytes32,(uint8,uint16),bytes,address,(address[],(uint8,address,address,address,bytes32)[])))" \
  "${DATA}" --json)"

echo "# Generated by read-prepared.sh from ${TX_HASH}"
echo "# Paste into the env used by: make safe-apply-install PLUGIN_PREFIX=${PREFIX}"
echo "${DECODED}" | PREFIX="${PREFIX}" python3 -c '
import json, os, subprocess, sys

prefix = os.environ["PREFIX"]

# Positional, against the known event shape — not scraped. Index 3 is the plugin, index 4 is
# PreparedSetupData(helpers, permissions).
decoded = json.load(sys.stdin)[0]
plugin = decoded[3]
helpers = decoded[4][0]
perms = decoded[4][1]

if not perms:
    sys.exit("error: the event carried no permissions; that cannot apply cleanly")

# Derived the way `hashHelpers` does — keccak256(abi.encode(address[])) — so the value cannot be
# mistyped, and an empty helper list still hashes correctly rather than being left blank.
encoded = subprocess.run(
    ["cast", "abi-encode", "f(address[])", "[" + ",".join(helpers) + "]"],
    capture_output=True, text=True, check=True,
).stdout.strip()
helpers_hash = subprocess.run(
    ["cast", "keccak", encoded], capture_output=True, text=True, check=True,
).stdout.strip()

conditioned = [p for p in perms if int(p[3], 16) != 0]

print(f"{prefix}_PLUGIN_ADDRESS={plugin}")
print(f"{prefix}_HELPERS_HASH={helpers_hash}")
print(f"{prefix}_PERM_OPS=" + ",".join(str(p[0]) for p in perms))
print(f"{prefix}_PERM_WHERE=" + ",".join(p[1] for p in perms))
print(f"{prefix}_PERM_WHO=" + ",".join(p[2] for p in perms))
print(f"{prefix}_PERM_IDS=" + ",".join(p[4] for p in perms))
print()
print(f"# {len(perms)} permission(s), {len(helpers)} helper(s) - order preserved as emitted.")

if conditioned:
    sys.stderr.write(
        f"error: {len(conditioned)} permission(s) carry a condition; SafeActions encodes "
        "NO_CONDITION and applyInstallation hashes the condition into the setup id, so the "
        "generated action would be rejected. Extend the generator before proceeding.\n"
    )
    sys.exit(2)
'
